export type EnemyFactionMemberRow = {
  member_id: number;
  faction_id: number;
  name: string;
  level: number | null;
  position: string | null;
  days_in_faction: number | null;
  company_type: string | null;
  company_rating: number | null;
  company_id: number | null;
  is_revivable: number | null;
  ff_battlestats: number | null;
  ff_battlestats_updated_at: number | null;
  bsp_battlestats: number | null;
  bsp_battlestats_updated_at: number | null;
  networth: number | null;
  networth_updated_at: number | null;
  networth_attempted_at: number | null;
  networth_attempt_count: number | null;
  networth_error: string | null;
  networth_key_source: string | null;
  status_state?: string | null;
  status_description?: string | null;
  last_action_status?: string | null;
  last_action_timestamp?: number | null;
  plane_image_type?: string | null;
  travel_origin?: string | null;
  travel_destination?: string | null;
  travel_signature?: string | null;
  travel_detected_at?: number | null;
  travel_started_after?: number | null;
  travel_started_before?: number | null;
  estimated_arrival_at?: number | null;
  estimated_arrival_earliest?: number | null;
  estimated_arrival_latest?: number | null;
  travel_trip_destination?: string | null;
  travel_trip_type?: string | null;
  travel_trip_inferred_at?: number | null;
  status_updated_at?: number | null;
  updated_at: number;
};

export type CurrentScoutingWar = {
  id: number;
  name: string;
  status?: string | null;
  enemy_faction_id: number;
  war_type: string | null;
  practical_start_time: number;
  practical_finish_time: number | null;
  official_start_time: number | null;
  enemy_scouting_status_checked_at: number | null;
};
